/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.acme;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Curse extends org.apache.avro.specific.SpecificExceptionBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"error\",\"name\":\"Curse\",\"namespace\":\"com.acme\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence message$;

  public Curse() {
    super();
  }
  
  public Curse(Object value) {
    super(value);
  }

  public Curse(Throwable cause) {
    super(cause);
  }

  public Curse(Object value, Throwable cause) {
    super(value, cause);
  }
  
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message$;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message$ = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message$' field.
   */
  public java.lang.CharSequence getMessage$() {
    return message$;
  }

  /**
   * Sets the value of the 'message$' field.
   * @param value the value to set.
   */
  public void setMessage$(java.lang.CharSequence value) {
    this.message$ = value;
  }

  /** Creates a new Curse RecordBuilder */
  public static com.acme.Curse.Builder newBuilder() {
    return new com.acme.Curse.Builder();
  }
  
  /** Creates a new Curse RecordBuilder by copying an existing Builder */
  public static com.acme.Curse.Builder newBuilder(com.acme.Curse.Builder other) {
    return new com.acme.Curse.Builder(other);
  }
  
  /** Creates a new Curse RecordBuilder by copying an existing Curse instance */
  public static com.acme.Curse.Builder newBuilder(com.acme.Curse other) {
    return new com.acme.Curse.Builder(other);
  }
  
  /**
   * RecordBuilder for Curse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificErrorBuilderBase<Curse>
    implements org.apache.avro.data.ErrorBuilder<Curse> {

    private java.lang.CharSequence message$;

    /** Creates a new Builder */
    private Builder() {
      super(com.acme.Curse.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.acme.Curse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Curse instance */
    private Builder(com.acme.Curse other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }

    @Override
    public com.acme.Curse.Builder setValue(Object value) {
      super.setValue(value);
      return this;
    }
    
    @Override
    public com.acme.Curse.Builder clearValue() {
      super.clearValue();
      return this;
    }

    @Override
    public com.acme.Curse.Builder setCause(Throwable cause) {
      super.setCause(cause);
      return this;
    }
    
    @Override
    public com.acme.Curse.Builder clearCause() {
      super.clearCause();
      return this;
    }

    /** Gets the value of the 'message$' field */
    public java.lang.CharSequence getMessage$() {
      return message$;
    }
    
    /** Sets the value of the 'message$' field */
    public com.acme.Curse.Builder setMessage$(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message$ = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'message$' field has been set */
    public boolean hasMessage$() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'message$' field */
    public com.acme.Curse.Builder clearMessage$() {
      message$ = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Curse build() {
      try {
        Curse record = new Curse(getValue(), getCause());
        record.message$ = fieldSetFlags()[0] ? this.message$ : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
