/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package service.demo;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EnumObj implements org.apache.thrift.TEnum {
  FOO(1),
  BAR(2);

  private final int value;

  private EnumObj(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EnumObj findByValue(int value) { 
    switch (value) {
      case 1:
        return FOO;
      case 2:
        return BAR;
      default:
        return null;
    }
  }
}
